context:
  version: "2.16.0"

package:
  name: felix
  version: ${{ version }}

source:
  url: https://github.com/kyoheiu/felix/archive/v${{ version }}.tar.gz
  sha256: 9fb0a1b120e3171883c8150792808e6871d052190ed8b9bcb0807970545285c6

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - felix --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: tui file manager with vim-like key mapping
  homepage: https://github.com/kyoheiu/felix
  repository: https://github.com/kyoheiu/felix

extra:
  recipe-maintainers:
    - danielnachun
